### PR TITLE
[#219] Show progress bar above verification tool controls

### LINKED ISSUE #219: A means of displaying completion of current verification-page
The verification-pages currently display a total of all suggestions for that particular page, and opening the filter will display the numbers of suggestions against a particular status, but there's no quick overview of how much of verification process has been completed for a particular page.

### PR DESCRIPTION
**Pull request by zarino**
Fixes #219.

@mhl @tmtmtmtm @rich-cassidy do you feel this gives a clear enough picture of your "progress"? Or should we highlight _only_ done/reverted statements?

screen shot 2018-07-13 at 10 22 46

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
@zarino I'm worried that this is going in the opposite direction to where we really want: it draws even more attention to internal states which we should be trying to hide from the user as much as possible. Most of this just seems like confusing jargon. *Maybe* if this could be reframed much more concretely around actions I could take it might work better?

**Comment by zarino** [comment]
@tmtmtmtm It’s a simple fix to have the progress bar differentiate between fewer states, all the way down to simply showing "done" and "not done". I just wasn’t sure where you’d want to cut that distinction. Perhaps we could chat about it, when you’re next free?

If we’re attempting to hide some of the states from people in the progress bar, I guess it also makes sense to start hiding them elsewhere in the UI, like in the state filter dropdown?

**Comment by zarino** [comment]
Closing this without merge because:

* Other recent changes (showing all statements at once, and subtotals in the state filter `<select>`) communicate "progress" sufficiently.
* We’re aiming to hide the states/types (like “reconcilable”, “actionable”) as much as possible, because they’re confusing, so it feels wrong to be adding a component that puts them front and centre.
* Discussion in #219 suggests we’re mostly happy with what we’ve already got.

**Comment by tmtmtmtm** [comment]
I'm re-opening this because the switch in #379 means we no longer have the counts anywhere else. I'd like to have #381 resolved first, though.

**Pull request closed without merging**
